### ISSUE TITLE
Review SQS requests from all regions

### ISSUE THREAD

**Issue by raanglada** [Diang-Tech/.github#4]
- Adrian cuando tengas chance revisa esto, medio raro que en todas las regiones tengamos uso de SQS

![Image](https://github.com/user-attachments/assets/a3aca373-4907-4c6c-a770-3073667d4cfc)

**Comment by ayeja153** [comment]
Estuve revisando y ese servicio no se usa en ninguna region, es posible que internamente lo use algun servicio de los que usamos pero no le veo logica a eso. Es posible escribir a soporte de AWS ?

**Comment by raanglada** [comment]
claro que si, tenemos soporte basico, has hecho reportes a soporte? sino es buena oportunidad para aprender, ya yo lo he hecho pero es bueno que tengas esa experiencia, escribe generico y el pie de firma que sea DiAng Tech DevOps Team
